### ISSUE TITLE
Epic 3 - MSME User Group Job Stories

### ISSUE THREAD

**Issue by rparrapy** [open-contracting/credere-backend#30]
- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] Provide information not in OCDS
- [x] SME option to change email
- [x] Submission complete feedback
- [x] Email notifications to update on progress
- [ ] Reminder to complete application
- [x] #107
- [x] Contact email and phone number
- [x] Frequently asked questions
- [x] #108
